export const itemData = [
  {
    img: "/images/men_casio_1.jpg",
    title: "Casio",
    desc: "Men's G Shock Grey Resin Grey Dial",
    count: 3,
    gender: "man",
    price:130,
  },
  {
    img: "/images/men_casio_2.jpg",
    title: "Casio",
    desc: "Men's G Shock Grey Resin Grey Dial",
    count: 1,
    gender: "man",
    price:99,
  },
  {
    img: "/images/men_casio_3.jpg",
    title: "Casio",
    desc: "Men's G Shock Grey Resin Grey Dial",
    count: 2,
    gender: "man",
    price:112,
  },
  {
    img: "/images/men_casio_4.jpg",
    title: "Casio",
    desc: "Men's G Shock Grey Resin Grey Dial",
    count: 3,
    gender: "man",
    price:155,
  },
  {
    img: "/images/men_casio_5.jpg",
    title: "Casio",
    desc: "Men's G Shock Grey Resin Grey Dial",
    count: 5,
    gender: "man",
    price:70,
  },
  {
    img: "/images/men_casio_6.jpg",
    title: "Casio",
    desc: "Men's G Shock Grey Resin Grey Dial",
    count: 1,
    gender: "man",
    price:89,
  },
  {
    img: "/images/women_casio_1.jpg",
    title: "Casio",
    desc: "Women's G Shock Grey Resin Grey Dial",
    count: 3,
    gender: "woman",
    price:55,
  },
  {
    img: "/images/women_casio_2.jpg",
    title: "Casio",
    desc: "Women's G Shock Grey Resin Grey Dial",
    count: 2,
    gender: "woman",
    price:155,
  },
  {
    img: "/images/women_casio_3.jpg",
    title: "Casio",
    desc: "Women's G Shock Grey Resin Grey Dial",
    count: 3,
    gender: "woman",
    price:505,
  },
  {
    img: "/images/women_tissot_1.jpg",
    title: "Tissot",
    desc: "Women's T-MY Lady Stainless Steel Mother of Pearl Dial Watch",
    count: 3,
    gender: "woman",
    price:200,
  },
  {
    img: "/images/women_tissot_2.jpg",
    title: "Tissot",
    desc: "Women's T-MY Lady Stainless Steel Mother of Pearl Dial Watch",
    count: 2,
    gender: "woman",
    price:100,
  },
  {
    img: "/images/women_tissot_3.jpg",
    title: "Tissot",
    desc: "Women's T-MY Lady Stainless Steel Mother of Pearl Dial Watch",
    count: 1,
    gender: "woman",
    price:90,
  },
  {
    img: "/images/men_tissot_1.jpg",
    title: "Tissot",
    desc: "Men's T-MY Stainless Steel Mother of Pearl Dial Watch",
    count: 4,
    gender: "man",
    price:300,
  },
  {
    img: "/images/men_tissot_2.jpg",
    title: "Tissot",
    desc: "Men's T-MY Stainless Steel Mother of Pearl Dial Watch",
    count: 1,
    gender: "man",
    price:70,
  },
  {
    img: "/images/men_tissot_3.jpg",
    title: "Tissot",
    desc: "Men's T-MY Stainless Steel Mother of Pearl Dial Watch",
    count: 2,
    gender: "man",
    price:220,
  },
  {
    img: "/images/men_tissot_4.jpg",
    title: "Tissot",
    desc: "Men's T-MY Stainless Steel Mother of Pearl Dial Watch",
    count: 1,
    gender: "man",
    price:110,
  },
];
